# Generated by Django 3.2 on 2022-07-04 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='text',
            field=models.TextField(default='null', max_length=255),
            preserve_default=False,
        ),
    ]
